# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['development']
    pull_request:
        branches: ['development']

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        env:
            AWS_APP_ID_DEVELOPMENT: ${{ secrets.AWS_APP_ID_DEVELOPMENT }}
            AWS_REGION: 'us-east-1'

        steps:
            - uses: actions/checkout@v4
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::314146338510:role/GitHubAction-AssumeRoleWithAction
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: ${{ env.AWS_REGION }}
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'npm'
            - name: Clean install
              run: npm ci
            - name: Generate Amplify Outputs
              run: npx ampx generate outputs --branch development --app-id "$AWS_APP_ID_DEVELOPMENT"
            - name: Build
              run: npm run build --if-present
            - name: Check Formatting
              run: npm run prettier:check
            - name: Lint
              run: npm run lint
            - name: Run Unit Tests
              run: npm test
